name: OpenUI5 CICD

# Controls when the action will run. 
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: ChloePlanet/github-tag-action@master
        id: tag-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          INITIAL_VERSION: 0.0.0
          
      - name: Docker Login
        uses: docker/login-action@v1.5.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }} --tag ${{ github.repository }}:latest

      - name: Push versioned Docker Image
        run: docker push ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }}

      - name: Push latest Docker Image
        run: docker push ${{ github.repository }}:latest
